name: Build GH Pages

on:
  push:
    branches:
      - master

jobs:
  initialize:
    name: Initialize repo, test lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Set up project
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Run tests
        run: yarn test:coverage

      - name: Set up git credentials
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config --local user.name "$USER_NAME"
          git config --local user.email "$USER_EMAIL"

      - name: Deploy to GitHub Pages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DEPLOY_BRANCH: gh-pages
          STATIC_FOLDER: dist
        run: |
          bash ./.github/workflows/build.bash
